stages:
  - getInv
  - updateSrc

image: jcomer3943/ubuntu:flask

variables:
  varPath: vars/$CI_COMMIT_REF_NAME
  dataPath: data/ucs

getPhyInv:
  stage: getInv
  artifacts:
    paths:
      - data/ucs
    expire_in: 1 hour
  script:
    - python3 intersight/ucsInventory-v2.py --type svrSummary
  only:
    - master

getDiskInv:
  stage: getInv
  artifacts:
    paths:
      - data/ucs
    expire_in: 1 hour
  script:
    - python3 intersight/ucsInventory-v2.py --type diskInventory
  only:
    - master

getVmHostInv:
  stage: getInv
  artifacts:
    paths:
      - data/ucs
    expire_in: 1 hour
  script:
    - python3 intersight/ucsInventory-v2.py --type vmmHost
  only:
    - master

getVmInv:
  stage: getInv
  artifacts:
    paths:
      - data/ucs
    expire_in: 1 hour
  script:
    - python3 intersight/ucsInventory-v2.py --type vmmInventory
  only:
    - master

updateSrc:
  stage: updateSrc
  artifacts:
    paths:
      - data/ucs
    expire_in: 1 hour
  script:
    - git config --global user.name jeff.comer
    - git config --global user.email jeff.comer@gitlab.com
    - git pull origin master
    - git add data/*
    - git remote set-url --push origin http://gl-ucs-token:7ptfVzxxhDmgqns4Qv95@172.16.14.132/jeff.comer/gl-ucs.git
    - git commit -m "updating source with inventory csv data"
    - git push origin $CI_COMMIT_REF_NAME -o ci.skip
  needs: ["getPhyInv", "getDiskInv", "getVmHostInv", "getVmInv"]
  only:
    - master