stages:
  - getInv

image: jcomer3943/ubuntu:flask

variables:
  varPath: vars/$CI_COMMIT_REF_NAME
  dataPath: data/ucs

getPhyInv:
  stage: getInv
  script:
    - python3 intersight/ucsInventory-v2.py --type svrSummary
    - sleep 60
  only:
    - master

getDiskInv:
  stage: getInv
  script:
    - python3 intersight/ucsInventory-v2.py --type diskInventory
    - sleep 60
  only:
    - master

getVmHostInv:
  stage: getInv
  script:
    - python3 intersight/ucsInventory-v2.py --type vmmHost
    - sleep 60
  only:
    - master

getVmInf:
  stage: getInv
  script:
    - python3 intersight/ucsInventory-v2.py --type vmmInventory
    - sleep 60
  only:
    - master