stages:
  - claimDevices
  - getInv
  - updateSrc


variables:
  varPath: vars/$CI_COMMIT_REF_NAME
  dataPath: data/ucs
  TF_VAR_varPath: vars/master
  TF_VAR_imcSeedFile: ../../vars/master/imc/hostIpAddrs.csv

claimDevices:
  stage: claimDevices
  image: jc3943/ubuntu-tfe:20220911
  script:
    - python3 imc/imcNetSet.py -u admin -p DEVP@ssw0rd -i $varPath/imc/hostIpAddrs.csvntp_servers
    - cd intersight/devClaims
    - terraform init
    - terraform apply -var-file=master.tfvars -auto-approve
    - cd ../../
    - python3 intersight/intersightDevClaimStatus.py -u https://dev-intersight.some.domain.com -i $varPath/imc/hostIpAddrs.csv

getPhyInv:
  stage: getInv
  artifacts:
    paths:
      - data/ucs
    expire_in: 1 hour
  image: jcomer3943/ubuntu:flask
  script:
    - python3 intersight/ucsInventory-v2.py --type svrSummary
  only:
    - master

getDiskInv:
  stage: getInv
  artifacts:
    paths:
      - data/ucs
    expire_in: 1 hour
  image: jcomer3943/ubuntu:flask
  script:
    - python3 intersight/ucsInventory-v2.py --type diskInventory
  only:
    - master

getVmHostInv:
  stage: getInv
  artifacts:
    paths:
      - data/ucs
    expire_in: 1 hour
  image: jcomer3943/ubuntu:flask
  script:
    - python3 intersight/ucsInventory-v2.py --type vmmHost
  only:
    - master

getVmInv:
  stage: getInv
  artifacts:
    paths:
      - data/ucs
    expire_in: 1 hour
  image: jcomer3943/ubuntu:flask
  script:
    - python3 intersight/ucsInventory-v2.py --type vmmInventory
  only:
    - master

updateSrc:
  stage: updateSrc
  artifacts:
    paths:
      - data/ucs
    expire_in: 1 hour
  image: jcomer3943/ubuntu:flask
  script:
    - git config --global user.name jeff.comer
    - git config --global user.email jeff.comer@gitlab.com
    - git checkout -b master
    - git add data/*
    - git remote set-url --push origin http://gl-ucs-token:7ptfVzxxhDmgqns4Qv95@172.16.14.132/jeff.comer/gl-ucs.git
    - git commit -m "updating source with inventory csv data"
    - git push origin $CI_COMMIT_REF_NAME -o ci.skip
  needs: ["getPhyInv", "getDiskInv", "getVmHostInv", "getVmInv"]
  only:
    - master