stages:
  - getInv
  - updateSrc

image: jcomer3943/ubuntu:flask

variables:
  varPath: vars/$CI_COMMIT_REF_NAME
  dataPath: data/ucs

getPhyInv:
  stage: getInv
  artifacts:
    paths:
      data/ucs/
    expire_in: 1 hour
  script:
    - python3 intersight/ucsInventory-v2.py --type svrSummary
    - sleep 300
  only:
    - master

getDiskInv:
  stage: getInv
  artifacts:
    paths:
      data/ucs/
    expire_in: 1 hour
  script:
    - python3 intersight/ucsInventory-v2.py --type diskInventory
  only:
    - master

getVmHostInv:
  stage: getInv
  artifacts:
    paths:
      data/ucs/
    expire_in: 1 hour
  script:
    - python3 intersight/ucsInventory-v2.py --type vmmHost
  only:
    - master

getVmInf:
  stage: getInv
  artifacts:
    paths:
      data/ucs/
    expire_in: 1 hour
  script:
    - python3 intersight/ucsInventory-v2.py --type vmmInventory
  only:
    - master

upDateSrc:
  stage: updateSrc
  artifacts:
    paths:
      data/ucs/
    expire_in: 1 hour
    - sleep 300
  needs: ["getPhyInv", "getDiskInv", "getVmHostInv", "getVmInf"]
  only:
    - master