stages:
  - claimDevices
  - getInv
  - updateSrc
#  - createRepos
  - installOs


variables:
  varPath: vars/$CI_COMMIT_REF_NAME
  dataPath: data/ucs
  TF_VAR_varPath: vars/$CI_COMMIT_REF_NAME
  TF_VAR_imcSeedFile: ../../vars/$CI_COMMIT_REF_NAME/imc/hostIpAddrs.csv

claimDevices:
  stage: claimDevices
  image: jc3943/ubuntu-tfe:20220911
  script:
    - python3 imc/imcNetSet.py -u admin -p DEVP@ssw0rd -i $varPath/imc/hostIpAddrs.csv
    - cd intersight/devClaims
    - terraform init
    - terraform apply -var-file=master.tfvars -auto-approve
    - cd ../../
    - python3 intersight/intersightDevClaimStatus.py -u https://dev-intersight.thor.iws.navy.mil -i $varPath/imc/hostIpAddrs.csv
    - sleep 180
  only:
    - imcPwrOpt

getPhyInv:
  stage: getInv
  artifacts:
    paths:
      - data/ucs
    expire_in: 1 hour
  image: jcomer3943/ubuntu:flask
  script:
    - python3 intersight/ucsInventory-v2.py --type svrSummary
  only:
    - imcPwrOpt

getDiskInv:
  stage: getInv
  artifacts:
    paths:
      - data/ucs
    expire_in: 1 hour
  image: jcomer3943/ubuntu:flask
  script:
    - python3 intersight/ucsInventory-v2.py --type diskInventory
  only:
    - imcPwrOpt

getVmHostInv:
  stage: getInv
  artifacts:
    paths:
      - data/ucs
    expire_in: 1 hour
  image: jcomer3943/ubuntu:flask
  script:
    - python3 intersight/ucsInventory-v2.py --type vmmHost
  only:
    - imcPwrOpt

getVmInv:
  stage: getInv
  artifacts:
    paths:
      - data/ucs
    expire_in: 1 hour
  image: jcomer3943/ubuntu:flask
  script:
    - python3 intersight/ucsInventory-v2.py --type vmmInventory
  only:
    - imcPwrOpt

updateSrc:
  stage: updateSrc
  artifacts:
    paths:
      - data/ucs
    expire_in: 1 hour
  image: jcomer3943/ubuntu:flask
  script:
    - git config --global user.name jeff.comer
    - git config --global user.email jeff.comer@gitlab.com
    - git checkout -b imcPwrOpt
    - git add data/*
    - git remote set-url --push origin http://gl-ucs-token:df7Ttj4FJbGRk1ee-yLp@172.16.14.132/jeff.comer/gl-ucs.git
    - git commit -m "updating source with inventory csv data"
    - git push origin $CI_COMMIT_REF_NAME -o ci.skip
  needs: ["getPhyInv", "getDiskInv", "getVmHostInv", "getVmInv"]
  only:
    - imcPwrOpt

# createRepos:
#   stage: createRepos
#   image: jc3943/ubuntu-tfe:20220911
#   script:
#     - cd bm-install/create_repos
#     - terraform init
#     - terraform apply --var-file=../../vars/master/terraform/create_repos.tfvars -auto-approve
#     - cd ../../

installOs:
  stage: installOs
  image: jc3943/ubuntu-tfe:20220911
  script:
    - cd bm-install/os_install_bulk
    - terraform init
    - terraform apply --var-file=../../vars/master/terraform/rhel_install.tfvars -auto-approve
    - cd ../../
  only:
    - imcPwrOpt