stages:
  - getInv
  - updateSrc

image: jcomer3943/ubuntu:flask

variables:
  varPath: vars/$CI_COMMIT_REF_NAME
  dataPath: data/ucs

getPhyInv:
  stage: getInv
  artifacts:
    untracked: true
  script:
    - python3 intersight/ucsInventory-v2.py --type svrSummary
  only:
    - master

getDiskInv:
  stage: getInv
  artifacts:
    untracked: true
  script:
    - python3 intersight/ucsInventory-v2.py --type diskInventory
  only:
    - master

getVmHostInv:
  stage: getInv
  artifacts:
    untracked: true
  script:
    - python3 intersight/ucsInventory-v2.py --type vmmHost
  only:
    - master

getVmInf:
  stage: getInv
  artifacts:
    untracked: true
  script:
    - python3 intersight/ucsInventory-v2.py --type vmmInventory
  only:
    - master

upDateSrc:
  stage: updateSrc
  artifacts:
    untracked: true
  script:
    - sleep 300
  dependencies:
    - getInv
  only:
    - master